/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define ADD 0
#define SUB 1
#define MUL 2
#define DIV 3

struct CALCULATOR {
	int op;
	double arg1;
	double arg2;
	int number;
	double result;
};
typedef struct CALCULATOR CALCULATOR;

#define CALCBAKERY_PROG 0x20000001
#define CALCULATOR_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALC_GET_INDEX 1
extern  int * calc_get_index_1(void *, CLIENT *);
extern  int * calc_get_index_1_svc(void *, struct svc_req *);
#define CALC_SERV 2
extern  double * calc_serv_1(struct CALCULATOR *, CLIENT *);
extern  double * calc_serv_1_svc(struct CALCULATOR *, struct svc_req *);
extern int calcbakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALC_GET_INDEX 1
extern  int * calc_get_index_1();
extern  int * calc_get_index_1_svc();
#define CALC_SERV 2
extern  double * calc_serv_1();
extern  double * calc_serv_1_svc();
extern int calcbakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_CALCULATOR (XDR *, CALCULATOR*);

#else /* K&R C */
extern bool_t xdr_CALCULATOR ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
